[package]
name = "karlsen-wrpc-server"
description = "Karlsen wRPC server"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
async-trait.workspace = true
borsh = { workspace = true, features = ["rc"] }
futures.workspace = true
karlsen-consensus-core.workspace = true
karlsen-core.workspace = true
karlsen-grpc-client.workspace = true
karlsen-notify.workspace = true
karlsen-rpc-core.workspace = true
karlsen-rpc-macros.workspace = true
karlsen-rpc-service.workspace = true
karlsen-utils.workspace = true
log.workspace = true
num_cpus.workspace = true
paste.workspace = true
serde = { workspace = true, features = ["rc"] }
thiserror.workspace = true
tokio.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
workflow-rpc.workspace = true

[target.'cfg(unix)'.dependencies]
# Adding explicitely the openssl dependency here is needed for a successful build with zigbuild
# as used in the release deployment in GitHub CI
# see: https://github.com/rust-cross/cargo-zigbuild/issues/127
openssl = { version = "0.10", features = ["vendored"] }
